name: PostgreSQL Backup

on:
  workflow_dispatch:  # Manual trigger support
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 2 AM UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install PostgreSQL Client
      run: sudo apt-get install -y postgresql-client

    - name: Perform Database Backup
      env:
        PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: |
        pg_dump \
          --host=dpg-ctdigk3v2p9s73ai5dog-a.frankfurt-postgres.render.com \
          --port=5432 \
          --username=siams_user \
          --dbname=siams \
          --format=custom \
          --file=backup_$(date +%Y%m%d).dump
