name: PostgreSQL Backup

on:
  workflow_dispatch:  # Manual trigger support
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 2 AM UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install PostgreSQL 16.x
      run: |
        echo "Installing PostgreSQL 16..."
        sudo apt-get update
        sudo apt-get -y install wget
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo apt-get update
        sudo apt-get -y install postgresql-client-16

    - name: Perform Database Backup
      env:
        PGPASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: |
        echo "Running pg_dump..."
        pg_dump \
          --host=dpg-ctdigk3v2p9s73ai5dog-a.frankfurt-postgres.render.com \
          --port=5432 \
          --username=siams_user \
          --dbname=siams \
          --format=custom \
          --file=backup_$(date +%Y%m%d).dump
