name: CI Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SIAMS/SIAMS.sln

    - name: Build the application
      run: dotnet build SIAMS/SIAMS.sln --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test SIAMS.Tests/SIAMS.Tests.csproj --configuration Release --verbosity normal

    - name: Check for Vulnerable Packages
      run: dotnet list package --vulnerable

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'csharp'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'SIAMS'
        path: '.'
        format: 'HTML'


